spring:
  cloud:
    stream:
      kafka:
        binder:
          #brokers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:29092}
          brokers: 121.89.198.164:29092
          auto-add-partitions: true
          min-partition-count: 3
      bindings:
        prices-in-0:
          #类似于topic/exchange
          destination: com.mycompany.bitcoin.api.price
          content-type: application/json
          group: bitcoinClientGroup
          consumer:
            max-attempts: 4
            back-off-initial-interval: 10000

  sleuth:
    sampler:
      probability: 0.5

management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, metrics, mappings
  endpoint:
    health:
      show-details: always
server:
  port: 8081
